### ISSUE TITLE
Error while running demo

### ISSUE THREAD

**Issue by sheriumair** [verificatum/verificatum-vmn#4]
I am getting errors while running demo. When I run 'info_files' I get error as follows

Generate info files... 
  Making directories of servers.... done.
  Generating protocol stub file...Exception in thread "main" com.verificatum.protocol.ProtocolError: Failed to add default value!
	at com.verificatum.protocol.com.BullBoardBasicHTTPGen.addDefault(BullBoardBasicHTTPGen.java:129)
	at com.verificatum.protocol.com.BullBoardBasicHTTPWGen.addDefault(BullBoardBasicHTTPWGen.java:79)
	at com.verificatum.protocol.ProtocolBBGen.addDefault(ProtocolBBGen.java:110)
	at com.verificatum.protocol.elgamal.ProtocolElGamalGen.addDefault(ProtocolElGamalGen.java:198)
	at com.verificatum.protocol.ProtocolGen.defaultPrivateInfo(ProtocolGen.java:356)
	at com.verificatum.ui.info.InfoTool.main(InfoTool.java:973)
Caused by: com.verificatum.ui.info.InfoException: Value out of domain! Value does not match expression! (http://sheriub-HP-Pavilion-15-Notebook-PC:8040 is not urlport)
	at com.verificatum.ui.info.Info.addValue(Info.java:182)
	at com.verificatum.protocol.com.BullBoardBasicHTTPGen.addDefault(BullBoardBasicHTTPGen.java:124)
	... 5 more
Caused by: com.verificatum.ui.info.InfoException: Value does not match expression! (http://sheriub-HP-Pavilion-15-Notebook-PC:8040 is not urlport)
	at com.verificatum.ui.info.NetField.validate(NetField.java:88)
	at com.verificatum.ui.info.NetField.parse(NetField.java:95)
	at com.verificatum.ui.info.Info.addValue(Info.java:180)
	... 6 more

Most recent command executed at
Party 1 failed with exit code 1.

Demo command failed! Aborting.

**Comment by verificatum** [comment]
This error is triggered because the following is not a valid domain name or IP address:

sheriub-HP-Pavilion-15-Notebook-PC

This is not a bug. This is a deliberate design decision. There are three ways to deal with this: (1) use a real domain name, (2) use an IP address directly, or (3) patch the code to allow your computer name instead of a domain name.
